name: Mirror Repo via SSH

on:
  push:
    branches:
      - main           # Only trigger on push to main
  pull_request:
    branches:
      - main           # Trigger when PR targets main
    types:
      - opened
      - synchronize    # Trigger when new commits are pushed to the PR
      - reopened
  workflow_dispatch:   # Optional manual trigger

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MIRROR_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Mirror repository over SSH
        run: |
          git config --global user.name "EC"
          git config --global user.email "me@ceduth.dev"

          git clone --mirror git@github.com:ceduth/ytdt-claims-pipeline.git
          cd private-repo.git

          git remote set-url --push origin git@github.com:ceduth-jfp/ytdt-claims-pipeline.git

          git push --mirror

